### ISSUE TITLE
Exception converting to Protobuf

### ISSUE THREAD

**Issue by iamceph** [iamceph/resulter#5]
When trying to convert Resultable into ProtoResultable, `NullPointerException` can occur.

This happens mainly if the supplied Resultable has `null` message.

```
java.lang.NullPointerException: null
	at com.iamceph.resulter.core.model.ProtoResultable$Builder.setMessage(ProtoResultable.java:754)
	at com.iamceph.resulter.core.extension.ConvertorExtensionImpl.convert(ConvertorExtensionImpl.java:83)
	at com.iamceph.resulter.core.model.ResultableImpl$1.convert(ResultableImpl.java:58)
	at com.iamceph.resulter.core.Resultable$Convertor.grpc(Resultable.java:272)
```

**Comment by iamceph** [comment]
Fixed in version 1.1.6.
